TRIBITS_PACKAGE_DEFINE_DEPENDENCIES(
  LIB_REQUIRED_PACKAGES
    DataTransferKitUtils
    DataTransferKitInterface
    DataTransferKitIntrepidAdapters
    Teuchos
    Tpetra
    Shards
    Intrepid
    STKUtil
    STKTopology
    STKMesh
  TEST_REQUIRED_PACKAGES
    DataTransferKitOperators
    DataTransferKitC_API
    STKIO
    STKUnit_tests
    STKUnit_test_utils
  LIB_REQUIRED_TPLS
    MPI
  )
